### ISSUE TITLE
It's suddenly stopped working for me...

### ISSUE THREAD

**Issue by superkick** [eramdam/fold-imports#5]
Really like this extension but recently it has stopped working - I also no longer have the ability to manually fold the imports (there's no chevron in the gutter allowing me to do that?) 

I
![Screenshot 2020-06-11 at 14 39 49](https://user-images.githubusercontent.com/15162932/84391837-68af2c00-abf1-11ea-8aff-d518cfc9412c.png)

As for when it stopped I'm unsure - appears to coincide with the last VSC update. 

Any suggestions on what to try next? I've enabled debug statements in the config but unsure where to see their logging outputs.

Cheers
S.

**Comment by eramdam** [comment]
> Really like this extension but recently it has stopped working - I also no longer have the ability to manually fold the imports (there's no chevron in the gutter allowing me to do that?)

The chevron thing is made by VSCode itself. My extension only calls the `Fold` action on the first line of imports to tell VSCode to fold, so if somehow the block isn't allowed to be folded, I can't do much 😕 

FWIW I'm running the latest VScode as well (1.46.0) and nothing changed so I'm really not sure what could be going on 😞

**Comment by superkick** [comment]
Thanks for getting back to me, looks like it's a problem with my local build then. Will try disabling all my other extensions and see if it fixes it. Thanks again 👍🏼👍🏼
